// Alérgenos: basados en ingredientes del PDF + tabla de alérgenos pág. 7
// X = contiene, T = puede contener traza
// Se muestran solo los que contiene (X) o traza (T marcado como 't')
// ⚠️ Verificar contra tabla oficial antes de publicar

export const ALERGENOS = {
  gluten:      { emoji: '🌾', label: 'Gluten' },
  crustaceos:  { emoji: '🦐', label: 'Crustáceos' },
  huevos:      { emoji: '🥚', label: 'Huevos' },
  pescado:     { emoji: '🐟', label: 'Pescado' },
  cacahuetes:  { emoji: '🥜', label: 'Cacahuetes' },
  soja:        { emoji: '🫘', label: 'Soja' },
  leche:       { emoji: '🥛', label: 'Leche' },
  frutosSecos: { emoji: '🌰', label: 'Frutos de cáscara' },
  apio:        { emoji: '🥬', label: 'Apio' },
  mostaza:     { emoji: '🌿', label: 'Mostaza' },
  sesamo:      { emoji: '🌱', label: 'Sésamo' },
  sulfitos:    { emoji: '⚗️', label: 'Sulfitos' },
  altramuces:  { emoji: '🌼', label: 'Altramuces' },
  moluscos:    { emoji: '🐚', label: 'Moluscos' },
}

export const CATEGORIAS = [
  { id: 'empezar',    label: 'Para empezar' },
  { id: 'autor',      label: 'De autor' },
  { id: 'galicia',    label: 'Made in Galicia' },
  { id: 'veggies',    label: 'Veggies' },
  { id: 'entrepanes', label: 'Entrepanes' },
  { id: 'ensaladas',  label: 'Ensaladas' },
  { id: 'postres',    label: 'Postres' },
]

export const PLATOS = [
  // ─── PARA EMPEZAR ────────────────────────────────────────────────────────
  {
    cat: 'empezar',
    nombre: 'Chipirones de la Ría',
    desc: 'Chipirones de la ría con alioli cítrico.',
    precio: '11,5',
    recomendado: true,
    alergenos: ['gluten', 'moluscos', 'huevos'],
  },
  {
    cat: 'empezar',
    nombre: 'Langostinos Kataifi',
    desc: 'Langostinos jugosos envueltos en crujiente pasta kataifi, acompañados de nuestra irresistible salsa teriyaki. (3 unid. / 6 unid.)',
    precio: '12,9',
    mediaRacion: '7,0',
    recomendado: true,
    alergenos: ['gluten', 'crustaceos', 'soja', 'sesamo'],
  },
  {
    cat: 'empezar',
    nombre: 'Camperitos de pollo de corral',
    desc: 'Deliciosas tiras de pechuga de pollo empanadas en crujiente panko. Acompañadas de salsa de miel y mostaza (8 unid).',
    precio: '11,9',
    recomendado: true,
    alergenos: ['gluten', 'mostaza'],
  },
  {
    cat: 'empezar',
    nombre: 'Aros de cebolla crujiente a la cerveza',
    desc: 'Aros de cebolla crujientes acompañados de una crema de queso de jalapeños y pimientos de Padrón escogidos los que no pican (8 unid).',
    precio: '8,9',
    alergenos: ['gluten', 'leche'],
  },
  {
    cat: 'empezar',
    nombre: 'Croquetas cremosas de jamón ibérico',
    desc: 'Croquetas cremosas con textura y sabor ibérico. (4 unid. / 9 unid.)',
    precio: '9,5',
    mediaRacion: '4,9',
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'empezar',
    nombre: 'Croquetas melosas de chipirones',
    desc: 'Cremosas croquetas de chipirones en su tinta con bechamel de textura suave y cremosa, con salsa alioli casera. (4 unid. / 8 unid.)',
    precio: '9,9',
    mediaRacion: '5,5',
    alergenos: ['gluten', 'leche', 'huevos', 'moluscos'],
  },
  {
    cat: 'empezar',
    nombre: 'Combi croquetas jamón + chipirones',
    desc: 'La mejor combinación: croquetas de jamón ibérico y melosas de chipirones (4+4 unid).',
    precio: '9,5',
    alergenos: ['gluten', 'leche', 'huevos', 'moluscos'],
  },
  {
    cat: 'empezar',
    nombre: 'Alitas de pollo a la barbacoa',
    desc: 'Deliciosas y crujientes alitas de pollo marinadas con salsa barbacoa (8 unid).',
    precio: '11,9',
    alergenos: ['gluten', 'sulfitos'],
  },

  // ─── DE AUTOR — Chefs Gallegos ───────────────────────────────────────────
  {
    cat: 'autor',
    nombre: 'Urbana Fina',
    desc: 'Pan crujiente con carne de vaca vieja madurada, base de lechuga, tartar de tomate sazonado, queso DOP San Simón da Costa fundido, pepinos marinados frescos y agridulces, salsa de huevo campero frito Pazo de Vilane y mayonesa casera coronada con patata fina y crujiente.',
    precio: '15,9',
    chef: 'Chef Héctor López',
    restaurante: 'Restaurante España · Lugo',
    recomendado: true,
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'autor',
    nombre: 'Urbana Antollo Galego',
    desc: 'Carne galega de vaca madurada con smash de Rixóns, queso de Arzúa-Ulloa, un toque de cremoso de grelo e pan tradicional espolvoreado con pimentón doce/picante como na casa dos teus avós.',
    precio: '16,9',
    chef: 'Chefs Kike Piñeiro y Eloy Cancela',
    restaurante: 'A Horta D\'Obradoiro · Santiago',
    recomendado: true,
    alergenos: ['gluten', 'leche'],
  },
  {
    cat: 'autor',
    nombre: 'Urbana Corea',
    desc: 'Pan crujiente con carne de vaca vieja madurada, queso DOP San Simón da Costa a golpe de calor, pepinillo agridulce, mayonesa kimchi, tomate seco, rúcula y salsa barbacoa de ajo negro.',
    precio: '15,9',
    chef: 'Chef Víctor Fernández',
    restaurante: 'Morrofino · Santiago',
    recomendado: true,
    glutenFree: true,
    alergenos: ['leche', 'huevos', 'soja', 'mostaza'],
  },
  {
    cat: 'autor',
    nombre: 'Urbana Indómita',
    desc: 'Pan crujiente gallego, Vaca Vieja 200 g, crema fundente de queso, tomate cherry confitado, pimiento de Padrón tatemado con ajo tostado y albahaca fresca.',
    precio: '16,9',
    chef: 'Chef Martín Vázquez',
    restaurante: 'Indómito · Santiago',
    recomendado: true,
    alergenos: ['gluten', 'leche'],
  },

  // ─── MADE IN GALICIA ─────────────────────────────────────────────────────
  {
    cat: 'galicia',
    nombre: 'Urbana Clásica',
    desc: 'Pan crujiente con Vaca Rubia Gallega, queso, tomate, lechuga, cebolla y salsa Urbana Rosé.',
    precio: '13,0',
    alergenos: ['gluten', 'leche', 'huevos', 'mostaza'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana Cuarto de Libra',
    desc: 'Pan crujiente con Vaca Rubia Gallega, lechuga, tomate natural, cebolla roja, queso cheddar, pepinillos, cebolla crujiente y salsa Urbana Rosé.',
    precio: '13,0',
    alergenos: ['gluten', 'leche', 'huevos', 'mostaza'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana Real',
    desc: 'Pan crujiente con Vaca Rubia Gallega, lechuga, queso de cabra al grill, cebolla caramelizada y salsa Urbana Rosé.',
    precio: '12,9',
    alergenos: ['gluten', 'leche'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana Piamonte',
    desc: 'Pan crujiente con Vaca Rubia Gallega, mermelada de tomate, crujiente de cebolla, salsa gorgonzola, lechuga, bacon ahumado y braseado.',
    precio: '13,9',
    recomendado: true,
    alergenos: ['gluten', 'leche'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana Campera',
    desc: 'Pan crujiente con Vaca Rubia Gallega, lechuga de roble, mozzarella, cebolla crujiente, queso philadelphia con panceta braseada, huevo campero Pazo de Vilane y miel ecológica de castaño.',
    precio: '14,5',
    recomendado: true,
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana Mejicana',
    desc: 'Pan crujiente con Vaca Rubia Gallega, lechuga, tomate natural, cebolla roja, jalapeños, cheddar, guacamole casero y salsa chilli. Acompañada de patatas fritas con tabasco.',
    precio: '14,0',
    glutenFree: true,
    alergenos: ['leche', 'huevos'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana Tártara',
    desc: 'Pan crujiente gallego, Rubia Gallega 190 g, salsa cremosa de encurtidos, cebolla roja encurtida, rabanito fresco, mezclum y lascas de parmesano.',
    precio: '14,5',
    alergenos: ['gluten', 'leche', 'mostaza', 'huevos'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana British',
    desc: 'Pan crujiente con Vaca Rubia Gallega, lechuga, mermelada de tomate, queso cheddar, bacon y huevo frito.',
    precio: '13,9',
    recomendado: true,
    glutenFree: true,
    alergenos: ['leche', 'huevos'],
  },
  {
    cat: 'galicia',
    nombre: 'Urbana Jalapeña',
    desc: 'Pan crujiente con Vaca Rubia Gallega, crema jalapeña de queso, lechuga troceada, cebolla crujiente, rodaja de jalapeño, doble cheddar fundido, cebolla caramelizada, panceta crujiente y yema de huevo.',
    precio: '14,5',
    alergenos: ['gluten', 'leche', 'huevos'],
  },

  // ─── VEGGIES ─────────────────────────────────────────────────────────────
  {
    cat: 'veggies',
    nombre: 'Urbana Rosé',
    desc: 'Pan crujiente con carne vegana, queso cheddar veggie, hoja de roble, tomate, cebolla y exquisita salsa rosa vegana.',
    precio: '13,9',
    alergenos: ['gluten', 'leche'],
  },
  {
    cat: 'veggies',
    nombre: 'Urbana Berenjena',
    desc: 'Pan crujiente gallego, burger vegetal, berenjena dorada y crujiente, tomate confitado, rúcula fresca y mayonesa agridulce.',
    precio: '13,9',
    alergenos: ['gluten', 'huevos'],
  },

  // ─── ENTREPANES ──────────────────────────────────────────────────────────
  {
    cat: 'entrepanes',
    nombre: 'Dechipis',
    desc: 'Absolutely delicious chipis crujientes con lechuga de mar, alioli cítrico y un toque de lima.',
    precio: '10,9',
    alergenos: ['gluten', 'moluscos', 'huevos', 'pescado'],
  },
  {
    cat: 'entrepanes',
    nombre: 'Rustic Way',
    desc: 'Una delicia rústica de panceta crujiente, queso de Arzúa suave y cremoso, rematado con rúcula fresca.',
    precio: '10,9',
    alergenos: ['gluten', 'leche'],
  },
  {
    cat: 'entrepanes',
    nombre: 'Urbana Corralita',
    desc: 'Pan crujiente y tiras de pollo empanado en panko (4 unid), queso cheddar, salsa Urbana Rosé, cebolla caramelizada, lechuga fresca y tomate.',
    precio: '12,5',
    alergenos: ['gluten', 'leche', 'huevos'],
  },

  // ─── ENSALADAS ───────────────────────────────────────────────────────────
  {
    cat: 'ensaladas',
    nombre: 'Cebreiro Mood',
    desc: 'Mezcla de lechugas frescas y brotes, huevo a baja temperatura, jamón y Queixo do Cebreiro. Todas nuestras ensaladas incluyen ración de pan semitostado.',
    precio: '10,5',
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'ensaladas',
    nombre: 'Kataifi y Guacamole',
    desc: 'Mezcla de lechugas frescas y brotes, tomates cherry, delicioso guacamole, cacahuetes garrapiñados, langostinos kataifi y queso parmesano. Incluye pan semitostado.',
    precio: '12,9',
    recomendado: true,
    alergenos: ['gluten', 'crustaceos', 'cacahuetes', 'leche'],
  },
  {
    cat: 'ensaladas',
    nombre: 'Ensalada César',
    desc: 'Hoja de roble y brotes aderezados con vinagreta y salsa césar, tomate cherry, pollo crunchy, lascas de grana padano y picatostes. Incluye pan semitostado.',
    precio: '10,9',
    recomendado: true,
    alergenos: ['gluten', 'leche', 'huevos', 'pescado', 'mostaza'],
  },

  // ─── POSTRES ─────────────────────────────────────────────────────────────
  {
    cat: 'postres',
    nombre: 'Cremosa de queso',
    desc: 'Cremosa tarta de queso fundida con mermelada de arándano.',
    precio: '5,9',
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'postres',
    nombre: 'Muerte por chocolate',
    desc: 'Bizcocho con dos capas de chocolate intenso decorado con topping de chocolate negro y crema inglesa.',
    precio: '5,9',
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'postres',
    nombre: 'Carrot especial',
    desc: 'Tarta de zanahoria con helado Ace cremoso, crujientes choco zetas y dulce baño de mango.',
    precio: '5,9',
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'postres',
    nombre: 'Capricho de chocolate',
    desc: 'Delicioso coulant de chocolate derretido en el interior, acompañado de una bola de helado de vainilla bañada en chocolate y crujiente almendra.',
    precio: '5,9',
    alergenos: ['gluten', 'leche', 'huevos', 'frutosSecos'],
  },
  {
    cat: 'postres',
    nombre: 'Tres chocolates',
    desc: 'Una tarta de locura con tres chocolates y el mejor tipo de galleta: la crujiente.',
    precio: '4,5',
    alergenos: ['gluten', 'leche', 'huevos'],
  },
  {
    cat: 'postres',
    nombre: 'Helado artesano',
    desc: 'Escoge 2 bolas del sabor que más te guste: Nata, vainilla, chocolate y ACE (sin alérgenos).',
    precio: '4,9',
    glutenFree: true,
    alergenos: ['leche'],
  },
  {
    cat: 'postres',
    nombre: 'Blueberry & Cheese',
    desc: 'Deliciosa crema de queso con galleta oreo y una base de arándano fresco. Sin galleta: libre de gluten.',
    precio: '4,9',
    alergenos: ['gluten', 'leche', 'huevos'],
  },
]
